### ISSUE TITLE
Request the source of the reference data (공간정보 데이터 출처 문의)

### ISSUE THREAD

**Issue by youngjour** [ansup0402/KoALA_Nx#1]
Thanks for your work, KoALA_Nx. 
While I'm reproducing this plugin on QGIS, I found this model needs the reference data, such as road network, population, neighborhood facilities. 

As you suggested, there are the website links for these datasets (VWorld).
However, these links are not working. 
Would you mind checking the sources of reference data again?

안녕하세요, 
KoALA 및 KoALA_Nx 플러그인을 만들어주셔서 감사합니다. 
해당 플러그인을 활용해보려고 하는데, 공간 레이어 데이터를 따로 다운로드 받아야하더군요. 
혹시 공간 레이어 데이터들을 다운로드 받을 수 있는 출처를 알려주실 수 있나요?
Readme에 링크가 붙어있는데, 아마 VWorld에서 해당 주소가 바뀐 것 같습니다.
행정경계/법정경계, 도로네트워크, 용도별 건축물 데이터들의 종류가 여럿이고 내용도 조금씩 달라서 정확한 모델을 구현하려고 문의드립니다. 

감사합니다.

**Comment by ansup0402** [comment]
관심 가져 주셔서 감사합니다...
아마 데이터 관리기관이 바뀐듯합니다. 
링크는 수정해 놓았습니다.
그리고 데이터의 경우 특별한 출처의 형식만을 요하는 것은 아닙니다.. 
필수적인 필드만 있다면 어떤 데이터도 다 사용 가능합니다.
감사합니다.
